---
kind: pipeline
type: kubernetes
name: Test

platform:
  os: linux
  arch: amd64

trigger:
  event:
    - pull_request
    - push
    - tag

services:
- name: mongo
  image: mongo:latest

steps:
- name: "Test"
  image: node:latest
  depends_on: ["clone"]
  commands:
    - echo 'Test!'
