version: '3.7'

volumes:
  go-tools:
    driver: local

services:
  tugboat:
    build:
      context: .
    environment:
      - ENV=dev
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_ORGANIZATION=${GITHUB_ORGANIZATION}
      - KUBECONFIG=/root/.kube/config
    volumes:
      - go-tools:/go/bin
      - ${KUBECONFIG}:/root/.kube/config:ro
      - ~/.aws/:/root/.aws/:ro
      - ~/.ssh/:/root/.ssh/:ro
